### ISSUE TITLE
Can you port the module to drupal 9?

### ISSUE THREAD

**Issue by enagy12** [Web-Wave/ww-angularjs-drupal8#1]
I've already used the module in Drupal 8. I should use it under drupal 9 now. I modified the following line in the ww_angularjs_drupal8.info.yml file:
core: 8.x
to:
core_version_requirement: ^ 8.7.7 || ^ 9

When I tried to enable the module, it got the following error message:
`ReflectionException type: Class \ Drupal \ ww_angularjs_drupal8 \ Controller \ wwAngularjsDrupal8Controller does not exist message in ReflectionMethod -> __ construct () function (EntityResolverManager.php file line 128).
`
Can you help me what have to modify to use the module under drupal 9?

**Comment by Web-Wave** [comment]
Hello @enagy12, 

Thanks for your message, I will be not able to port the module on Drupal 9 as I never work on this version yet.
You are free to migrate the module on Drupal 9 and share with us your changes.

Thanks !

**Comment by Web-Wave** [comment]
Issue closed since there is no message anymore.
